spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seec_erp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 789632145yjj
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nju.edu.erp.model.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeHandlersPackage: com.nju.edu.erp.enums.handlers
jwt:
  secret: 6e12d69c-af21-4cc2-b32d-3fa949b50106
  expire: 86400000
